# Generated by Django 6.0.5 on 2026-06-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0011_remove_user_balance_remove_user_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='', max_length=256),
        ),
    ]
