# Generated by Django 6.0.5 on 2026-05-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usd', models.CharField(max_length=100)),
                ('eur', models.CharField(max_length=100)),
                ('rub', models.CharField(max_length=100)),
                ('gbp', models.CharField(max_length=100)),
                ('jpy', models.CharField(max_length=100)),
                ('chf', models.CharField(max_length=100)),
                ('cny', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'currency',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
