# Generated by Django 6.0.5 on 2026-06-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_user_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
