# Generated by Django 6.0.5 on 2026-06-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_user_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_auth',
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='', max_length=128),
        ),
    ]
