# Generated by Django 6.0.5 on 2026-06-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0007_alter_card_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.CharField(max_length=4),
        ),
    ]
